# Azure OpenAI Configuration
AZURE_OPENAI_API_KEY = "GAbqj97MHveLyKaLpDeDhsuJpMG9nRi5iqnsgFYVZgzPH19gpjsAJQQJ99BFACfhMk5XJ3w3AAABACOGIGov"
AZURE_OPENAI_ENDPOINT = "https://stormwhirlpool.openai.azure.com/"
AZURE_OPENAI_API_VERSION = "2024-12-01-preview"

# Model domyślny
AZURE_OPENAI_DEPLOYMENT_NAME = "gpt-4.1"
